// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/dashboard" | "/admin/kds" | "/admin/login" | "/admin/menu/categories" | "/admin/menu/items" | "/admin/menu/modifiers" | "/admin/reports" | "/admin/tables" | "/guest/active-orders" | "/guest/checkout" | "/guest/history" | "/guest/login" | "/guest/orders/[orderId]" | "/guest/payment/[orderId]" | "/guest/pending-payment" | "/guest/profile" | "/guest/register" | "/guest/review" | "/kitchen" | "/menu/guest" | "/waiter/login" | "/waiter/orders"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin/dashboard": {}
  "/admin/kds": {}
  "/admin/login": {}
  "/admin/menu/categories": {}
  "/admin/menu/items": {}
  "/admin/menu/modifiers": {}
  "/admin/reports": {}
  "/admin/tables": {}
  "/guest/active-orders": {}
  "/guest/checkout": {}
  "/guest/history": {}
  "/guest/login": {}
  "/guest/orders/[orderId]": { "orderId": string; }
  "/guest/payment/[orderId]": { "orderId": string; }
  "/guest/pending-payment": {}
  "/guest/profile": {}
  "/guest/register": {}
  "/guest/review": {}
  "/kitchen": {}
  "/menu/guest": {}
  "/waiter/login": {}
  "/waiter/orders": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
