// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/kds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kds">> = Specific
  const handler = {} as typeof import("../../../app/admin/kds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/menu/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu/categories">> = Specific
  const handler = {} as typeof import("../../../app/admin/menu/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/menu/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu/items">> = Specific
  const handler = {} as typeof import("../../../app/admin/menu/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/menu/modifiers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu/modifiers">> = Specific
  const handler = {} as typeof import("../../../app/admin/menu/modifiers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/tables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tables">> = Specific
  const handler = {} as typeof import("../../../app/admin/tables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/active-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/active-orders">> = Specific
  const handler = {} as typeof import("../../../app/guest/active-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/checkout">> = Specific
  const handler = {} as typeof import("../../../app/guest/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/history">> = Specific
  const handler = {} as typeof import("../../../app/guest/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/login">> = Specific
  const handler = {} as typeof import("../../../app/guest/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/guest/orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/payment/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/payment/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/guest/payment/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/pending-payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/pending-payment">> = Specific
  const handler = {} as typeof import("../../../app/guest/pending-payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/profile">> = Specific
  const handler = {} as typeof import("../../../app/guest/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/register">> = Specific
  const handler = {} as typeof import("../../../app/guest/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guest/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/review">> = Specific
  const handler = {} as typeof import("../../../app/guest/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/kitchen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kitchen">> = Specific
  const handler = {} as typeof import("../../../app/kitchen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/menu/guest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu/guest">> = Specific
  const handler = {} as typeof import("../../../app/menu/guest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/waiter/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/waiter/login">> = Specific
  const handler = {} as typeof import("../../../app/waiter/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/waiter/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/waiter/orders">> = Specific
  const handler = {} as typeof import("../../../app/waiter/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
